(ns gesso.live.browser.build
  "Physical build correspondence for generated Gesso Live browser artifacts.

   gesso.live.browser.artifact owns pure semantic correspondence metadata:
   BrowserArtifactStamp says exactly which BrowserAssemblyManifest a generated
   browser artifact is supposed to realize. This namespace owns the next,
   deliberately physical boundary: binding that stamp to the exact JavaScript
   bytes emitted by a build.

   A successful browser build records one closed ArtifactReceipt containing:

     - the BrowserArtifactStamp derived from the exact preflighted assembly;
     - SHA-256 of the generated artifact bytes;
     - the generated artifact byte size.

   Later build/start tooling verifies both relations before trusting the generated
   artifact:

     current BrowserAssemblyManifest == receipt BrowserArtifactStamp
     current generated bytes          == receipt artifact descriptor

   A filename, timestamp, non-empty file, or matching assembly name is never
   treated as sufficient correspondence. Missing or malformed receipts fail
   closed. The receipt is build metadata only; it is not browser authority,
   authentication, or semantic runtime input.

   This namespace deliberately does not invoke cljs.main itself. Different
   applications may own different physical compiler commands, output paths, and
   bundling arrangements. The supported build path must call
   record-generated-artifact! immediately after successful emission and
   verify-generated-artifact! before consuming an existing generated artifact.
   Later wiring can make those calls unavoidable without duplicating the
   correspondence rules here."
  (:require
   [clojure.edn :as edn]
   [clojure.java.io :as io]
   [gesso.live.browser.artifact :as artifact])
  (:import
   (java.io BufferedInputStream FileInputStream)
   (java.nio.charset StandardCharsets)
   (java.nio.file AtomicMoveNotSupportedException
                   Files
                   Path
                   StandardCopyOption)
   (java.security MessageDigest)
   (java.util UUID)))

;; -----------------------------------------------------------------------------
;; Identity / closed vocabulary
;; -----------------------------------------------------------------------------

(def build-version
  1)

(def receipt-type
  :gesso.live.browser.build/artifact-receipt)

(def digest-algorithm
  :sha-256)

(def ^:private receipt-keys
  #{:gesso.live.browser.build/type
    :gesso.live.browser.build/version
    :artifact
    :stamp})

(def ^:private artifact-descriptor-keys
  #{:algorithm
    :digest
    :size})

(def ^:private receipt-suffix
  ".gesso-artifact.edn")

;; -----------------------------------------------------------------------------
;; Errors / shape helpers
;; -----------------------------------------------------------------------------

(defn- build-error
  ([kind message data]
   (build-error kind message data nil))
  ([kind message data cause]
   (ex-info
    message
    (merge
     {:error/type :gesso.live.browser.build/error
      :error/kind kind}
     data)
    cause)))

(defn- closed-map?
  [expected-keys value]
  (and
   (map? value)
   (= expected-keys
      (set (keys value)))))

(defn- sha-256-hex?
  [value]
  (and
   (string? value)
   (boolean
    (re-matches #"[0-9a-f]{64}" value))))

(defn- artifact-descriptor?
  [value]
  (and
   (closed-map? artifact-descriptor-keys value)
   (= digest-algorithm
      (:algorithm value))
   (sha-256-hex?
    (:digest value))
   (pos-int?
    (:size value))))

(defn receipt?
  "True when value is one closed current generated-browser ArtifactReceipt.

   Recognition proves only receipt shape. Semantic and physical correspondence
   are established by verify-generated-artifact!."
  [value]
  (and
   (closed-map? receipt-keys value)
   (= receipt-type
      (:gesso.live.browser.build/type value))
   (= build-version
      (:gesso.live.browser.build/version value))
   (artifact-descriptor?
    (:artifact value))
   (artifact/stamp?
    (:stamp value))))

;; -----------------------------------------------------------------------------
;; Physical artifact identity
;; -----------------------------------------------------------------------------

(defn receipt-path
  "Return the default sibling metadata path for generated artifact-path."
  [artifact-path]
  (str artifact-path receipt-suffix))

(defn- require-generated-artifact-file!
  [artifact-path]
  (let [file
        (io/file artifact-path)]
    (when-not (.isFile file)
      (throw
       (build-error
        :missing-generated-artifact
        "Generated Gesso browser artifact does not exist as a regular file."
        {:artifact-path (str artifact-path)})))
    (when-not (pos? (.length file))
      (throw
       (build-error
        :empty-generated-artifact
        "Generated Gesso browser artifact is empty."
        {:artifact-path (str artifact-path)})))
    file))

(defn- digest-bytes->hex
  [digest-bytes]
  (apply
   str
   (map
    (fn [byte-value]
      (format "%02x"
              (bit-and 0xff byte-value)))
    digest-bytes)))

(defn- sha-256-file
  [file]
  (let [digest
        (MessageDigest/getInstance "SHA-256")

        buffer
        (byte-array 16384)]
    (with-open [input
                (BufferedInputStream.
                 (FileInputStream. file))]
      (loop []
        (let [read-count
              (.read input buffer)]
          (when-not (= -1 read-count)
            (.update digest
                     buffer
                     0
                     read-count)
            (recur)))))
    (digest-bytes->hex
     (.digest digest))))

(defn artifact-descriptor
  "Return the exact physical identity of one non-empty generated browser file.

   The descriptor is portable closed data and intentionally excludes path and
   timestamp so moving the artifact/receipt pair does not change identity."
  [artifact-path]
  (let [file
        (require-generated-artifact-file!
         artifact-path)]
    {:algorithm digest-algorithm
     :digest (sha-256-file file)
     :size (.length file)}))

(defn artifact-receipt
  "Construct one closed ArtifactReceipt from a current BrowserAssemblyManifest
   and one already-generated browser artifact on disk.

   The manifest is revalidated by artifact/stamp and the file must exist and be
   non-empty. No metadata is written by this function."
  [manifest artifact-path]
  (let [value
        {:gesso.live.browser.build/type receipt-type
         :gesso.live.browser.build/version build-version
         :artifact (artifact-descriptor artifact-path)
         :stamp (artifact/stamp manifest)}]
    (when-not
     (receipt? value)
      (throw
       (build-error
        :invalid-generated-artifact-receipt
        "Gesso derived an invalid generated browser ArtifactReceipt."
        {:artifact-path (str artifact-path)
         :receipt value})))
    value))

;; -----------------------------------------------------------------------------
;; Receipt persistence
;; -----------------------------------------------------------------------------

(defn- path-parent
  [^Path path]
  (or
   (.getParent path)
   (.toAbsolutePath
    (.getParent
     (.toAbsolutePath path)))))

(defn- move-replacing!
  [^Path source ^Path target]
  (try
    (Files/move
     source
     target
     (into-array
      java.nio.file.CopyOption
      [StandardCopyOption/ATOMIC_MOVE
       StandardCopyOption/REPLACE_EXISTING]))
    (catch AtomicMoveNotSupportedException _
      (Files/move
       source
       target
       (into-array
        java.nio.file.CopyOption
        [StandardCopyOption/REPLACE_EXISTING]))))
  target)

(defn- write-edn-atomically!
  [metadata-path value]
  (let [target
        (.toPath
         (io/file metadata-path))

        parent
        (path-parent target)

        temp
        (.resolve
         parent
         (str
          "."
          (.getFileName target)
          "."
          (UUID/randomUUID)
          ".tmp"))

        bytes
        (.getBytes
         (str (pr-str value) "\n")
         StandardCharsets/UTF_8)]
    (Files/createDirectories
     parent
     (make-array java.nio.file.attribute.FileAttribute 0))
    (try
      (Files/write
       temp
       bytes
       (make-array java.nio.file.OpenOption 0))
      (move-replacing! temp target)
      (finally
        (Files/deleteIfExists temp)))))

(defn record-generated-artifact!
  "Record exact correspondence metadata for one successfully generated browser
   artifact.

   By default metadata is written beside the artifact at
   `<artifact>.gesso-artifact.edn`. Pass :receipt-path to place the receipt
   elsewhere when a build system has an explicit metadata directory.

   The JavaScript artifact must already exist and be non-empty. The receipt is
   written only after its semantic stamp and byte identity have both been
   derived successfully. Returns the receipt."
  ([manifest artifact-path]
   (record-generated-artifact!
    manifest
    artifact-path
    {}))
  ([manifest artifact-path {:keys [receipt-path]
                            :as options}]
   (let [unknown-options
         (seq
          (remove
           #{:receipt-path}
           (keys options)))]
     (when unknown-options
       (throw
        (build-error
         :unknown-record-options
         "Generated browser artifact recording received unsupported options."
         {:unknown-keys (set unknown-options)
          :allowed-keys #{:receipt-path}}))))
   (let [receipt
         (artifact-receipt
          manifest
          artifact-path)

         metadata-path
         (or receipt-path
             (gesso.live.browser.build/receipt-path
              artifact-path))]
     (write-edn-atomically!
      metadata-path
      receipt)
     receipt)))

(defn read-artifact-receipt!
  "Read and recognize one generated browser ArtifactReceipt from disk.

   Missing, unreadable, non-EDN, or structurally invalid metadata fails closed."
  [metadata-path]
  (let [file
        (io/file metadata-path)]
    (when-not (.isFile file)
      (throw
       (build-error
        :missing-artifact-receipt
        "Generated Gesso browser artifact receipt is missing."
        {:receipt-path (str metadata-path)})))
    (let [value
          (try
            (edn/read-string
             (slurp file :encoding "UTF-8"))
            (catch Throwable error
              (throw
               (build-error
                :unreadable-artifact-receipt
                "Generated Gesso browser artifact receipt could not be read as EDN."
                {:receipt-path (str metadata-path)}
                error))))]
      (when-not
       (receipt? value)
        (throw
         (build-error
          :invalid-artifact-receipt
          "Generated Gesso browser artifact receipt has an invalid or unsupported shape."
          {:receipt-path (str metadata-path)
           :receipt value})))
      value)))

;; -----------------------------------------------------------------------------
;; Mandatory correspondence check primitive
;; -----------------------------------------------------------------------------

(defn verify-generated-artifact!
  "Verify that one generated browser artifact exactly corresponds to the current
   BrowserAssemblyManifest and to the receipt written for its emitted bytes.

   Verification fails closed when:

     - the generated artifact is missing or empty;
     - the receipt is missing, unreadable, malformed, or from an unsupported
       receipt version;
     - the receipt's BrowserArtifactStamp does not correspond exactly to the
       current manifest;
     - the current artifact byte size or SHA-256 differs from the recorded
       descriptor.

   Returns the recognized receipt on success. This is the primitive that normal
   build/start tooling should invoke before consuming an existing generated
   application browser artifact."
  ([manifest artifact-path]
   (verify-generated-artifact!
    manifest
    artifact-path
    {}))
  ([manifest artifact-path {:keys [receipt-path]
                            :as options}]
   (let [unknown-options
         (seq
          (remove
           #{:receipt-path}
           (keys options)))]
     (when unknown-options
       (throw
        (build-error
         :unknown-verify-options
         "Generated browser artifact verification received unsupported options."
         {:unknown-keys (set unknown-options)
          :allowed-keys #{:receipt-path}}))))
   (let [metadata-path
         (or receipt-path
             (gesso.live.browser.build/receipt-path
              artifact-path))

         receipt
         (read-artifact-receipt!
          metadata-path)

         current-descriptor
         (artifact-descriptor
          artifact-path)]
     (try
       (artifact/require-correspondence!
        manifest
        (:stamp receipt))
       (catch clojure.lang.ExceptionInfo error
         (if (= :browser-artifact-correspondence-failed
                (:error/kind (ex-data error)))
           (throw
            (build-error
             :artifact-stamp-correspondence-failed
             "Generated Gesso browser artifact was built from a different browser assembly."
             {:artifact-path (str artifact-path)
              :receipt-path (str metadata-path)
              :correspondence
              (:correspondence
               (ex-data error))}
             error))
           (throw error))))

     (when-not
      (= (:artifact receipt)
         current-descriptor)
       (throw
        (build-error
         :generated-artifact-content-mismatch
         "Generated Gesso browser artifact bytes do not match the recorded build receipt."
         {:artifact-path (str artifact-path)
          :receipt-path (str metadata-path)
          :recorded (:artifact receipt)
          :current current-descriptor})))

     receipt)))
