(ns gesso.live.browser.build
  "Physical build correspondence for generated Gesso Live browser artifacts.

   gesso.live.browser.artifact owns pure semantic correspondence metadata:
   BrowserArtifactStamp says exactly which BrowserAssemblyManifest a generated
   browser artifact is supposed to realize. This namespace owns the next,
   deliberately physical boundary: binding that stamp to the exact JavaScript
   bytes emitted by a build.

   A successful browser build records one closed ArtifactReceipt containing:

     - the BrowserArtifactStamp derived from the exact preflighted assembly;
     - SHA-256 of the generated artifact bytes;
     - the generated artifact byte size.

   Later build/start tooling verifies both relations before trusting the generated
   artifact:

     current BrowserAssemblyManifest == receipt BrowserArtifactStamp
     current generated bytes          == receipt artifact descriptor

   A filename, timestamp, non-empty file, or matching assembly name is never
   treated as sufficient correspondence. Missing or malformed receipts fail
   closed. The receipt is build metadata only; it is not browser authority,
   authentication, or semantic runtime input.

   build-generated-artifact! owns the lower-level physical publication boundary:
   it stages bytes supplied by one emitter, derives exact semantic/physical
   correspondence before publication, publishes the generated bytes, writes the
   receipt atomically, and verifies the final pair before returning. Because an
   arbitrary emitter could ignore the supplied manifest, that primitive alone
   does not establish that the JavaScript actually embeds the manifest it is
   stamped with.

   build-application-artifact! is therefore the ordinary supported application
   boundary. Gesso derives one BrowserAssemblyManifest from the application
   declaration, generates the ClojureScript bootstrap wrapper that embeds that
   exact manifest, invokes the ClojureScript compiler over that generated source,
   and delegates publication/receipt verification to build-generated-artifact!.
   Application code may supply only a CLJS Var containing physical realization
   options; it does not get a second semantic assembly declaration in the
   generated entrypoint."
  (:require
   [clojure.edn :as edn]
   [clojure.java.io :as io]
   [clojure.string :as str]
   [gesso.live.browser.artifact :as artifact]
   [gesso.live.browser.entrypoint :as entrypoint])
  (:import
   (java.io BufferedInputStream FileInputStream PushbackReader StringReader)
   (java.nio.charset StandardCharsets)
   (java.nio.file AtomicMoveNotSupportedException
                   Files
                   Path
                   StandardCopyOption)
   (java.security MessageDigest)
   (java.util UUID)))

;; -----------------------------------------------------------------------------
;; Identity / closed vocabulary
;; -----------------------------------------------------------------------------

(def build-version
  1)

(def receipt-type
  :gesso.live.browser.build/artifact-receipt)

(def digest-algorithm
  :sha-256)

(def ^:private receipt-keys
  #{:gesso.live.browser.build/type
    :gesso.live.browser.build/version
    :artifact
    :stamp})

(def ^:private artifact-descriptor-keys
  #{:algorithm
    :digest
    :size})

(def ^:private receipt-suffix
  ".gesso-artifact.edn")

;; -----------------------------------------------------------------------------
;; Errors / shape helpers
;; -----------------------------------------------------------------------------

(defn- build-error
  ([kind message data]
   (build-error kind message data nil))
  ([kind message data cause]
   (ex-info
    message
    (merge
     {:error/type :gesso.live.browser.build/error
      :error/kind kind}
     data)
    cause)))

(defn- build-error?
  [error]
  (= :gesso.live.browser.build/error
     (:error/type (ex-data error))))

(defn- closed-map?
  [expected-keys value]
  (and
   (map? value)
   (= expected-keys
      (set (keys value)))))

(defn- sha-256-hex?
  [value]
  (and
   (string? value)
   (boolean
    (re-matches #"[0-9a-f]{64}" value))))

(defn- artifact-descriptor?
  [value]
  (and
   (closed-map? artifact-descriptor-keys value)
   (= digest-algorithm
      (:algorithm value))
   (sha-256-hex?
    (:digest value))
   (pos-int?
    (:size value))))

(defn receipt?
  "True when value is one closed current generated-browser ArtifactReceipt.

   Recognition proves only receipt shape. Semantic and physical correspondence
   are established by verify-generated-artifact!."
  [value]
  (and
   (closed-map? receipt-keys value)
   (= receipt-type
      (:gesso.live.browser.build/type value))
   (= build-version
      (:gesso.live.browser.build/version value))
   (artifact-descriptor?
    (:artifact value))
   (artifact/stamp?
    (:stamp value))))

;; -----------------------------------------------------------------------------
;; Physical artifact identity
;; -----------------------------------------------------------------------------

(defn receipt-path
  "Return the default sibling metadata path for generated artifact-path."
  [artifact-path]
  (str artifact-path receipt-suffix))

(defn- require-generated-artifact-file!
  [artifact-path]
  (let [file
        (io/file artifact-path)]
    (when-not (.isFile file)
      (throw
       (build-error
        :missing-generated-artifact
        "Generated Gesso browser artifact does not exist as a regular file."
        {:artifact-path (str artifact-path)})))
    (when-not (pos? (.length file))
      (throw
       (build-error
        :empty-generated-artifact
        "Generated Gesso browser artifact is empty."
        {:artifact-path (str artifact-path)})))
    file))

(defn- digest-bytes->hex
  [digest-bytes]
  (apply
   str
   (map
    (fn [byte-value]
      (format "%02x"
              (bit-and 0xff byte-value)))
    digest-bytes)))

(defn- sha-256-file
  [file]
  (let [digest
        (MessageDigest/getInstance "SHA-256")

        buffer
        (byte-array 16384)]
    (with-open [input
                (BufferedInputStream.
                 (FileInputStream. file))]
      (loop []
        (let [read-count
              (.read input buffer)]
          (when-not (= -1 read-count)
            (.update digest
                     buffer
                     0
                     read-count)
            (recur)))))
    (digest-bytes->hex
     (.digest digest))))

(defn artifact-descriptor
  "Return the exact physical identity of one non-empty generated browser file.

   The descriptor is portable closed data and intentionally excludes path and
   timestamp so moving the artifact/receipt pair does not change identity."
  [artifact-path]
  (let [file
        (require-generated-artifact-file!
         artifact-path)]
    {:algorithm digest-algorithm
     :digest (sha-256-file file)
     :size (.length file)}))

(defn artifact-receipt
  "Construct one closed ArtifactReceipt from a current BrowserAssemblyManifest
   and one already-generated browser artifact on disk.

   The manifest is revalidated by artifact/stamp and the file must exist and be
   non-empty. No metadata is written by this function."
  [manifest artifact-path]
  (let [value
        {:gesso.live.browser.build/type receipt-type
         :gesso.live.browser.build/version build-version
         :artifact (artifact-descriptor artifact-path)
         :stamp (artifact/stamp manifest)}]
    (when-not
     (receipt? value)
      (throw
       (build-error
        :invalid-generated-artifact-receipt
        "Gesso derived an invalid generated browser ArtifactReceipt."
        {:artifact-path (str artifact-path)
         :receipt value})))
    value))

;; -----------------------------------------------------------------------------
;; Receipt persistence
;; -----------------------------------------------------------------------------

(defn- path-parent
  [^Path path]
  (or
   (.getParent path)
   (.toAbsolutePath
    (.getParent
     (.toAbsolutePath path)))))

(defn- move-replacing!
  [^Path source ^Path target]
  (try
    (Files/move
     source
     target
     (into-array
      java.nio.file.CopyOption
      [StandardCopyOption/ATOMIC_MOVE
       StandardCopyOption/REPLACE_EXISTING]))
    (catch AtomicMoveNotSupportedException _
      (Files/move
       source
       target
       (into-array
        java.nio.file.CopyOption
        [StandardCopyOption/REPLACE_EXISTING]))))
  target)

(defn- write-edn-atomically!
  [metadata-path value]
  (let [target
        (.toPath
         (io/file metadata-path))

        parent
        (path-parent target)

        temp
        (.resolve
         parent
         (str
          "."
          (.getFileName target)
          "."
          (UUID/randomUUID)
          ".tmp"))

        bytes
        (.getBytes
         (str (pr-str value) "\n")
         StandardCharsets/UTF_8)]
    (Files/createDirectories
     parent
     (make-array java.nio.file.attribute.FileAttribute 0))
    (try
      (Files/write
       temp
       bytes
       (make-array java.nio.file.OpenOption 0))
      (move-replacing! temp target)
      (finally
        (Files/deleteIfExists temp)))))

(defn- publish-artifact-receipt!
  [artifact-path metadata-path receipt]
  (try
    (write-edn-atomically!
     metadata-path
     receipt)
    (catch Throwable error
      (throw
       (build-error
        :artifact-receipt-publication-failed
        "Gesso could not publish the generated browser ArtifactReceipt; the artifact must not be consumed until a matching receipt is published."
        {:artifact-path (str artifact-path)
         :receipt-path (str metadata-path)
         :artifact (:artifact receipt)
         :stamp (:stamp receipt)}
        error)))))

(defn record-generated-artifact!
  "Record exact correspondence metadata for one successfully generated browser
   artifact.

   By default metadata is written beside the artifact at
   `<artifact>.gesso-artifact.edn`. Pass :receipt-path to place the receipt
   elsewhere when a build system has an explicit metadata directory.

   The JavaScript artifact must already exist and be non-empty. The receipt is
   written only after its semantic stamp and byte identity have both been
   derived successfully. Returns the receipt."
  ([manifest artifact-path]
   (record-generated-artifact!
    manifest
    artifact-path
    {}))
  ([manifest artifact-path {:keys [receipt-path]
                            :as options}]
   (let [unknown-options
         (seq
          (remove
           #{:receipt-path}
           (keys options)))]
     (when unknown-options
       (throw
        (build-error
         :unknown-record-options
         "Generated browser artifact recording received unsupported options."
         {:unknown-keys (set unknown-options)
          :allowed-keys #{:receipt-path}}))))
   (let [receipt
         (artifact-receipt
          manifest
          artifact-path)

         metadata-path
         (or receipt-path
             (gesso.live.browser.build/receipt-path
              artifact-path))]
     (publish-artifact-receipt!
      artifact-path
      metadata-path
      receipt)
     receipt)))

(def ^:private edn-eof
  (Object.))

(defn- read-one-edn-form
  [text]
  (with-open [reader
              (PushbackReader.
               (StringReader. text))]
    (let [value
          (edn/read
           {:eof edn-eof}
           reader)]
      (when
       (identical? edn-eof value)
        (throw
         (IllegalArgumentException.
          "Artifact receipt contains no EDN form.")))
      (let [trailing
            (edn/read
             {:eof edn-eof}
             reader)]
        (when-not
         (identical? edn-eof trailing)
          (throw
           (IllegalArgumentException.
            "Artifact receipt contains more than one EDN form."))))
      value)))

(defn read-artifact-receipt!
  "Read and recognize exactly one generated browser ArtifactReceipt from disk.

   Missing, unreadable, non-EDN, multi-form, or structurally invalid metadata
   fails closed. Whitespace and comments after the one receipt form are allowed,
   but a second EDN value is never silently ignored."
  [metadata-path]
  (let [file
        (io/file metadata-path)]
    (when-not (.isFile file)
      (throw
       (build-error
        :missing-artifact-receipt
        "Generated Gesso browser artifact receipt is missing."
        {:receipt-path (str metadata-path)})))
    (let [value
          (try
            (read-one-edn-form
             (slurp file :encoding "UTF-8"))
            (catch Throwable error
              (throw
               (build-error
                :unreadable-artifact-receipt
                "Generated Gesso browser artifact receipt must contain exactly one readable EDN value."
                {:receipt-path (str metadata-path)}
                error))))]
      (when-not
       (receipt? value)
        (throw
         (build-error
          :invalid-artifact-receipt
          "Generated Gesso browser artifact receipt has an invalid or unsupported shape."
          {:receipt-path (str metadata-path)
           :receipt value})))
      value)))

;; -----------------------------------------------------------------------------
;; Mandatory correspondence check primitive
;; -----------------------------------------------------------------------------

(defn verify-generated-artifact!
  "Verify that one generated browser artifact exactly corresponds to the current
   BrowserAssemblyManifest and to the receipt written for its emitted bytes.

   Verification fails closed when:

     - the generated artifact is missing or empty;
     - the receipt is missing, unreadable, malformed, or from an unsupported
       receipt version;
     - the receipt's BrowserArtifactStamp does not correspond exactly to the
       current manifest;
     - the current artifact byte size or SHA-256 differs from the recorded
       descriptor.

   Returns the recognized receipt on success. This is the primitive that normal
   build/start tooling should invoke before consuming an existing generated
   application browser artifact."
  ([manifest artifact-path]
   (verify-generated-artifact!
    manifest
    artifact-path
    {}))
  ([manifest artifact-path {:keys [receipt-path]
                            :as options}]
   (let [unknown-options
         (seq
          (remove
           #{:receipt-path}
           (keys options)))]
     (when unknown-options
       (throw
        (build-error
         :unknown-verify-options
         "Generated browser artifact verification received unsupported options."
         {:unknown-keys (set unknown-options)
          :allowed-keys #{:receipt-path}}))))
   (let [metadata-path
         (or receipt-path
             (gesso.live.browser.build/receipt-path
              artifact-path))

         receipt
         (read-artifact-receipt!
          metadata-path)

         current-descriptor
         (artifact-descriptor
          artifact-path)]
     (try
       (artifact/require-correspondence!
        manifest
        (:stamp receipt))
       (catch clojure.lang.ExceptionInfo error
         (if (= :browser-artifact-correspondence-failed
                (:error/kind (ex-data error)))
           (throw
            (build-error
             :artifact-stamp-correspondence-failed
             "Generated Gesso browser artifact was built from a different browser assembly."
             {:artifact-path (str artifact-path)
              :receipt-path (str metadata-path)
              :correspondence
              (:correspondence
               (ex-data error))}
             error))
           (throw error))))

     (when-not
      (= (:artifact receipt)
         current-descriptor)
       (throw
        (build-error
         :generated-artifact-content-mismatch
         "Generated Gesso browser artifact bytes do not match the recorded build receipt."
         {:artifact-path (str artifact-path)
          :receipt-path (str metadata-path)
          :recorded (:artifact receipt)
          :current current-descriptor})))

     receipt)))

;; -----------------------------------------------------------------------------
;; Supported generated-artifact build orchestration
;; -----------------------------------------------------------------------------

(defn- temp-artifact-path
  [artifact-path]
  (let [target
        (.toPath
         (io/file artifact-path))

        parent
        (path-parent target)

        filename
        (str (.getFileName target))]
    (Files/createDirectories
     parent
     (make-array java.nio.file.attribute.FileAttribute 0))
    (.resolve
     parent
     (str
      ".gesso-stage."
      (UUID/randomUUID)
      "."
      filename))))

(defn- publish-generated-artifact!
  [staged-path artifact-path]
  (let [target
        (.toPath
         (io/file artifact-path))]
    (try
      (move-replacing! staged-path target)
      (catch Throwable error
        (throw
         (build-error
          :generated-artifact-publication-failed
          "Gesso could not publish the staged generated browser artifact."
          {:artifact-path (str artifact-path)
           :staged-path (str staged-path)}
          error))))))

(defn build-generated-artifact!
  "Run the supported fail-closed build boundary for one application browser
   artifact.

   emit! is called exactly once with a temporary sibling output path. It must
   emit the complete non-empty JavaScript artifact at that path or throw. The
   final artifact path is not replaced until the staged bytes can be stamped
   against the supplied current BrowserAssemblyManifest.

   On successful emission this function:

     1. derives a closed ArtifactReceipt from the staged bytes and manifest;
     2. atomically publishes the staged JavaScript where supported;
     3. atomically writes the receipt where supported;
     4. verifies the published artifact + receipt against the current manifest.

   If emission fails, the previously published artifact/receipt pair is left
   untouched. If publication or receipt writing fails, the operation fails
   closed and subsequent verification cannot bless mismatched bytes/metadata.

   :receipt-path may override the default sibling receipt path. No other options
   are accepted. Returns the final verified ArtifactReceipt.

   This is the lower-level physical publication primitive used by
   build-application-artifact!. Build systems that must own compilation themselves
   may use it deliberately, but an arbitrary emitter is a trusted build assumption:
   this function cannot prove that emitted JavaScript actually embeds manifest.
   Ordinary application builds should use build-application-artifact! instead.

   record-generated-artifact! and verify-generated-artifact! remain still lower-
   level integration primitives for build systems that must own publication
   separately."
  ([manifest artifact-path emit!]
   (build-generated-artifact!
    manifest
    artifact-path
    emit!
    {}))
  ([manifest artifact-path emit! {:keys [receipt-path]
                                  :as options}]
   (let [unknown-options
         (seq
          (remove
           #{:receipt-path}
           (keys options)))]
     (when unknown-options
       (throw
        (build-error
         :unknown-build-options
         "Generated browser artifact build received unsupported options."
         {:unknown-keys (set unknown-options)
          :allowed-keys #{:receipt-path}}))))

   (when-not
    (ifn? emit!)
     (throw
      (build-error
       :invalid-artifact-emitter
       "Generated browser artifact build requires an emission function."
       {:artifact-path (str artifact-path)
        :emitter emit!})))

   ;; Validate semantic assembly before invoking a physical compiler or touching
   ;; the previously published artifact. This keeps malformed application
   ;; assembly a construction/build failure rather than an emission failure.
   (artifact/stamp manifest)

   (let [staged-path
         (temp-artifact-path artifact-path)

         metadata-path
         (or receipt-path
             (gesso.live.browser.build/receipt-path
              artifact-path))]
     (try
       (try
         (emit! (str staged-path))
         (catch Throwable error
           ;; Preserve precise Gesso build failures produced by an owned emitter
           ;; (for example :clojurescript-compiler-unavailable). Arbitrary
           ;; physical/compiler failures still collapse to the generic emission
           ;; boundary below. This keeps structured repair information from being
           ;; hidden behind an implementation-detail wrapper.
           (if (build-error? error)
             (throw error)
             (throw
              (build-error
               :generated-artifact-emission-failed
               "Gesso browser artifact emission failed before a new artifact could be published."
               {:artifact-path (str artifact-path)
                :staged-path (str staged-path)}
               error)))))

       (let [receipt
             (artifact-receipt
              manifest
              (str staged-path))]
         (publish-generated-artifact!
          staged-path
          artifact-path)

         (publish-artifact-receipt!
          artifact-path
          metadata-path
          receipt)

         (verify-generated-artifact!
          manifest
          artifact-path
          {:receipt-path metadata-path}))
       (finally
         ;; Staging cleanup is physical hygiene, not semantic build success. A
         ;; cleanup failure must never replace the actual compiler/publication
         ;; exception that caused the build to fail.
         (try
           (Files/deleteIfExists staged-path)
           (catch Throwable _
             nil)))))))



;; -----------------------------------------------------------------------------
;; Supported application ClojureScript build
;; -----------------------------------------------------------------------------

(def application-build-version
  1)

(def ^:private application-build-option-keys
  #{:receipt-path
    :realization-options-var})

(defn- fully-qualified-symbol?
  [value]
  (and
   (symbol? value)
   (some? (namespace value))
   (seq (name value))))

(defn- require-realization-options-var!
  [manifest realization-options-var]
  (let [optimistic?
        (contains? (:features manifest) :optimistic)]
    (when (and optimistic?
               (nil? realization-options-var))
      (throw
       (build-error
        :missing-realization-options-var
        "BrowserAssemblyManifest enables optimism, so the application build requires one fully-qualified ClojureScript realization-options Var."
        {:manifest-name (:name manifest)
         :features (:features manifest)})))

    (when (and (some? realization-options-var)
               (not (fully-qualified-symbol?
                     realization-options-var)))
      (throw
       (build-error
        :invalid-realization-options-var
        "Application browser realization options must be named by one fully-qualified ClojureScript Var symbol."
        {:manifest-name (:name manifest)
         :realization-options-var realization-options-var})))

    realization-options-var))

(defn- generated-entrypoint-ns
  []
  (symbol
   (str
    "gesso.generated.browser.application_"
    (str/replace
     (str (UUID/randomUUID))
     "-"
     "_"))))

(defn- namespace-source-path
  [source-root ns-sym]
  (let [relative
        (-> (str ns-sym)
            (str/replace "." "/")
            (str/replace "-" "_"))]
    (io/file source-root (str relative ".cljs"))))

(defn- generated-namespace-symbol?
  [value]
  (and
   (symbol? value)
   (nil? (namespace value))
   (boolean
    (re-matches
     #"[A-Za-z_][A-Za-z0-9_.-]*"
     (name value)))))

(defn application-entrypoint-source
  "Return the generated ClojureScript source for one supported application
   browser entrypoint.

   manifest must be a current closed BrowserAssemblyManifest. The exact manifest
   value is embedded directly into the generated source and is therefore the same
   semantic value later used to stamp the generated JavaScript receipt.

   realization-options-var, when supplied, must be one fully-qualified CLJS Var
   symbol. Its namespace is required by the generated entrypoint and its value is
   passed only as the physical realization-options argument to bootstrap/init!.
   The application cannot override manifest-owned browser role, plan resolver,
   feature set, transport, or bootstrap identity through this generated source."
  [generated-ns manifest realization-options-var]
  (when-not (generated-namespace-symbol? generated-ns)
    (throw
     (build-error
      :invalid-generated-entrypoint-namespace
      "Generated application browser entrypoint requires one closed namespace symbol."
      {:generated-ns generated-ns})))

  (artifact/stamp manifest)
  (require-realization-options-var!
   manifest
   realization-options-var)

  (let [realization-ns
        (some-> realization-options-var namespace symbol)

        realization-local
        (some-> realization-options-var name symbol)]
    (str
     "(ns " generated-ns "\n"
     "  (:require\n"
     "   [gesso.live.browser.bootstrap :as bootstrap]"
     (when realization-ns
       (str "\n   [" realization-ns " :as application-realization]"))
     "))\n\n"
     "(def ^:private browser-assembly\n"
     "  '" (pr-str manifest) ")\n\n"
     "(defn ^:export init! []\n"
     "  (bootstrap/init!\n"
     "   browser-assembly"
     (when realization-local
       (str "\n   application-realization/" realization-local))
     "))\n\n"
     "(init!)\n")))

(defn- require-cljs-build-api!
  []
  (try
    (let [build
          (requiring-resolve 'cljs.build.api/build)

          inputs
          (requiring-resolve 'cljs.build.api/inputs)]
      (when-not (and build inputs)
        (throw
         (IllegalStateException.
          "cljs.build.api build functions did not resolve.")))
      {:build build
       :inputs inputs})
    (catch Throwable error
      (throw
       (build-error
        :clojurescript-compiler-unavailable
        "Supported application browser builds require ClojureScript on the JVM build classpath."
        {}
        error)))))

(defn- delete-tree-best-effort!
  [root]
  (let [root-file
        (io/file root)]
    (when (.exists root-file)
      (doseq [file (reverse (file-seq root-file))]
        (try
          (Files/deleteIfExists
           (.toPath file))
          (catch Throwable _
            nil))))))

(defn- emit-application-cljs!
  [manifest realization-options-var staged-artifact-path]
  (let [build-root
        (.toFile
         (Files/createTempDirectory
          "gesso-browser-application-"
          (make-array java.nio.file.attribute.FileAttribute 0)))

        source-root
        (io/file build-root "src")

        output-dir
        (io/file build-root "out")

        generated-ns
        (generated-entrypoint-ns)

        source-file
        (namespace-source-path
         source-root
         generated-ns)

        source
        (application-entrypoint-source
         generated-ns
         manifest
         realization-options-var)]
    (try
      (Files/createDirectories
       (.toPath (.getParentFile source-file))
       (make-array java.nio.file.attribute.FileAttribute 0))
      (spit source-file source :encoding "UTF-8")

      (let [{:keys [build inputs]}
            (require-cljs-build-api!)]
        (build
         (inputs (.getPath source-root))
         {:optimizations :advanced
          :output-dir (.getPath output-dir)
          :output-to (str staged-artifact-path)}))
      (finally
        (delete-tree-best-effort! build-root)))))

(defn build-application-artifact!
  "Build one application browser artifact through the ordinary Gesso-owned
   semantic + generated-source + physical publication path.

   declaration is the same application browser declaration accepted by
   gesso.live.browser.entrypoint/compile-browser-assembly!. Gesso resolves and
   preflights it exactly once into a BrowserAssemblyManifest. That exact manifest
   is then embedded into a generated ClojureScript bootstrap namespace and also
   supplied to build-generated-artifact! for the final receipt stamp.

   Options:

     :realization-options-var
       Optional fully-qualified CLJS Var symbol whose value contains only the
       physical realization options accepted by gesso.live.browser.bootstrap.
       It is required when the manifest enables optimism.

     :receipt-path
       Optional non-default ArtifactReceipt path.

   The ClojureScript compiler is loaded dynamically from the JVM build classpath
   and advanced-compiles the Gesso-generated wrapper. Application build code does
   not provide an emitter callback and therefore cannot accidentally stamp bytes
   produced from an unrelated semantic entrypoint while using this supported
   path.

   This correspondence remains relative to the trusted ClojureScript compiler
   implementation; it does not claim to prove the compiler itself. Returns the
   final verified ArtifactReceipt."
  ([declaration artifact-path]
   (build-application-artifact!
    declaration
    artifact-path
    {}))
  ([declaration artifact-path {:keys [receipt-path
                                      realization-options-var]
                               :as options}]
   (let [unknown-options
         (seq
          (remove
           application-build-option-keys
           (keys options)))]
     (when unknown-options
       (throw
        (build-error
         :unknown-application-build-options
         "Application browser build received unsupported options."
         {:unknown-keys (set unknown-options)
          :allowed-keys application-build-option-keys}))))

   (let [manifest
         (entrypoint/compile-browser-assembly!
          declaration)

         realization-options-var
         (require-realization-options-var!
          manifest
          realization-options-var)]
     (build-generated-artifact!
      manifest
      artifact-path
      (fn [staged-artifact-path]
        (emit-application-cljs!
         manifest
         realization-options-var
         staged-artifact-path))
      (cond-> {}
        receipt-path
        (assoc :receipt-path receipt-path))))))
